### ISSUE TITLE
SyntaxError: The requested module 'mp3-duration-estimate' does not provide an export named 'FetchDataReader'

### ISSUE THREAD

**Issue by yongzhihuang** [FactorialComplexity/mp3-duration-estimate#3]
Hi, I tried to run the example in a standalone Node script on Nodejs V12
I've set `  "type": "module"` in package.json and ran the script with experimental-modules flag
```
 node --experimental-modules index.js
```

but I encountered this error:
```
import createEstimator, { FetchDataReader } from 'mp3-duration-estimate'
                          ^^^^^^^^^^^^^^^
SyntaxError: The requested module 'mp3-duration-estimate' does not provide an export named 'FetchDataReader'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:91:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:106:20)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
```

Here's index.js
```
import createEstimator, { FetchDataReader } from 'mp3-duration-estimate'
 
// You can provide any Fetch API-compatible fetch function
import fetch from 'node-fetch'
 
const estimator = createEstimator(new FetchDataReader(fetch))
 
estimator('https://foo.com/test.mp3')
  .then(duration => console.log(duration))
  .catch(error => console.error(error))
```

Can yo tell me if you know how to fix? Thanks!

**Comment by yongzhihuang** [comment]
Figured it out, you need to do imports non es6 way:

const createEstimator = require('mp3-duration-estimate').default;
const FetchDataReader = require('mp3-duration-estimate').FetchDataReader;
const fetch = require('node-fetch');

const estimator = createEstimator(new FetchDataReader(fetch))

estimator('https://foo.com/test.mp3')
  .then(duration => console.log(duration))
  .catch(error => console.error(error))
